/*  We'll start by writing the function which reacts to the signal
    which is passed in the parameter sig.
    This is the function we will arrange to be called when a signal occurs.
    We print a message, then reset the signal handling for SIGINT
    (by default generated by pressing CTRL-C) back to the default behavior.
    Let's call this function ouch.  */


#include<stdio.h>
#include<unistd.h>
#include<signal.h>


void signalFun(int sig){
	
	printf("Signal received %d\n", sig);
	(void) signal(SIGINT, SIG_DFL);
}

int main(){
	
	(void) signal(SIGINT, signalFun);
	
	while(1){
		printf("Hello\n");
		usleep(100000);
	}
}


